### ISSUE TITLE
null-ls.lua:27: attempt to call field 'format' (a nil value)

### ISSUE THREAD

**Issue by angelus2014** [Allaman/nvim#10]
Hello,

First off, excuse me if this is something I've just missed or did wrong as I'm new to Neovim and totally new to a Lua based config. 

When I save a file, I'm getting the following error:
Error detected while processing BufWritePre Autocommands for "<buffer=4>":
Error executing lua callback: /Users/angelo/.config/nvim/lua/config/null-ls.lua:27: attempt to call field 'format' (a nil value)
stack traceback:
"alacritty.yml" 893L, 31333B written

It does save the changes, but I'm not quite clear what that error means. I'm on macOS (M1) with Neovim 0.7.2. Is the fact that I'm not on 0.8 the cause of this error or did I something wrong/miss something?

Thank you in advance!

---
With regards,

Angelo Machils

**Comment by Allaman** [comment]
Hello,

please try replacing [this line](https://github.com/Allaman/nvim/blob/main/lua/config/null-ls.lua#L27) with `vim.lsp.buf.formatting_sync()`

If I remember correctly this should be the only 0.8 setting regarding null-ls.

If you want to go on Neovim dev it is really easy with brew

1. Install with `brew install --HEAD neovim` 
2. Update with `brew reinstall nvim`

BTW: my config is only "tested", let's say used with Neovim dev and I don't pay attention to be backwards compatible 🙈

**Comment by angelus2014** [comment]
Hello,

Upgrading to the 0.8dev version was indeed the solution. Thank you!

btw, as I use Neomutt for my e-mail I'm still using 'regular' vim as the editor. Switching to Neovim is easy enough, but there is one vim script setting I can't seem to figure out how/where to put it in a Lua config. It's about having 'flowed' text in Neomutt which requires a setting in the Neomutt config, but also one in Vim: set fo+=w. I did some research, but I can't seem to be able to figure out where/how I should do this in Lua.
According to the Lua Neovim documentation, I should add `vim.cmd [[set formatoptions=croql]]`, but this just gets ignored (I put it in the options.lua file) as `set fo?` comes back with `formatoptions=ql`.
If I try `o.formatoptions:append({ "w" })`, it comes back with `formatoptions=1jql`.

Thank you for your help and your very nice configuration for Neovim!


---
With regards,

Angelo Machils

**Comment by Allaman** [comment]
Hello,

glad that it works!

Pls have a look at [this commit](https://github.com/Allaman/nvim/commit/35d8781322f443b6c36e9221fac003275ccbd354). I should work this way. I also use Neomutt but there was no need for this setting. Maybe it will work for me as well 😆 

> Thank you for your help and your very nice configuration for Neovim!
You are welcome 😄

**Comment by angelus2014** [comment]
Hello,

The output of `:set fo?` of Neovim, started on it's own is: tcqj and with the edits in the autocmd.lua file and when started from within Neomutt: jtcqlaw, so it is at least being picked up. But it still doesn't work, the resulting e-mail still has hard return in continuous lines. I previously asked a similar question in the Neomutt repo and there I was told to set up something like `vim -c 'setlocal textwidth=70 colorcolumn=75 ft=mail fo+=aw listchars=tab:→\\ ,trail:↓ list'`. And for Vim this works. If I exchange vim with nvim in that line, it doesn't anymore. The output of `:set fo?` in Vim is the same as the one in Neovim (when called from Neomutt).

But isn't there some 'formatting' plugin running when one saves a file in Neovim when using your config? Could it be that this removes/alters the e-mail?


---
With regards,

Angelo Machils

**Comment by Allaman** [comment]
Hmm but this is [expected](https://vim.fandom.com/wiki/Automatic_word_wrapping)? How has this worked on Vim? 
> The above methods do a "hard" wrap of your text, by inserting newline characters. 

Regarding formating plugin - no. All my formating is handled by null-ls which is not started in a mail buffer. Some "formating" is located in the autocmd.lua like removing trailing spaces.

**Comment by Allaman** [comment]
[This](https://github.com/Allaman/nvim/commit/c5596f99a1c5ce9f7d8b7780dbcdf053f2349609) is working for me! 😄

**Comment by angelus2014** [comment]
Hmmmm, it doesn't for me. The result is still:
<img width="1098" alt="Screenshot 2022-08-04 at 20 39 33" src="https://user-images.githubusercontent.com/7578963/182915638-e50d6e4f-d48d-4661-8ce3-dbdee6a85cb2.png">

But with a proper configuration of Vim (and also Neovim with a more barebones configuration):
<img width="1178" alt="Screenshot 2022-08-04 at 20 43 08" src="https://user-images.githubusercontent.com/7578963/182916125-bbc28f2e-53d4-41eb-b7b0-80f91c5815c2.png">

As you can see, at the recipients end, there are no 'funny' breaks in the middle of a sentence. Even though in Neomutt, it looks like this:
<img width="869" alt="Screenshot 2022-08-04 at 20 46 23" src="https://user-images.githubusercontent.com/7578963/182916806-1b6414d6-1db6-4019-9540-132e3a334b23.png">
In Vim and Neovim, one would see the same.

With Vim, it worked by entering the `set fo+=w` in an open session when Vim was called from Neomutt. Now, with that setting in Neomutt with the extended call of the editor, that is no longer needed. In Neomutt one puts `set text_flowed`.

I also tested a more barebones Lua Neovim config and there it works as well in the manner I described.


---
With regards,

Angelo Machils

p.s.: Just to be clear, the first two images are from a mailclient on the recipients side (in this testcase, myself, but with a GUI mailclient, MailMate).

**Comment by Allaman** [comment]
This is me writing the mail. As indicated by the line numbers this is one long line.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/12184268/182918203-227ed41b-a7a8-4a62-9ac5-213f0c7c575f.png">
This is the mail in Apple Mail
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/12184268/182918274-b0ddc30f-56d4-4dcd-8a68-df487075705c.png">

My Neomutt config calls nvim this way: `set editor="$EDITOR +':set spell spelllang=de,en'"`

**Comment by Allaman** [comment]
I just built the Docker image with my config and it looks good as well. After `set filetype=mail` each paragraph is only one line. Of course I can't send a mail out of the container cause of missing config

<img width="704" alt="image" src="https://user-images.githubusercontent.com/12184268/182921133-17206f9b-5da7-461f-a34e-7a54e2ace773.png">

This is how it looks without setting the filetype to mail. The lines go over the full window width
<img width="1898" alt="image" src="https://user-images.githubusercontent.com/12184268/182921459-b89b69c1-2963-4af8-adaa-1e4226b77216.png">

edit: Do you have Docker to test the config in a container?

**Comment by angelus2014** [comment]
Hello,

Yes, I have Docker, but I've just tested with the simpler call to Neovim inside Neomutt (the one that you use) and then it works as expected. I can understand (to an extend), why it was needed for Vim, but as I wrote, it also worked for a simpler setup with Neovim..... :) As a Sys Admin I don't like this kind of unexplained behaviour, but as a user, I'm happy that it's working now with your Neovim config.... :)

Thank you again, I will close the issue.


---
With regards,

Angelo Machils
