### ISSUE TITLE
Temporarily disabling autoformatting

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#11]
Does anyone happen to know the command or shortcut for temporarily disabling autoformatting? It was formatting my typescript in a way I didn't want, and didn't have time in the moment to dig too deeply into it.

While I was doing some digging earlier today, my guess is that I would need to manage these lines with a condition based on a variable? https://github.com/Allaman/nvim/blob/376c2531f17d2e4b752828d4a1ab202925d8bf1f/lua/config/null-ls.lua#L21-L30

**Comment by Allaman** [comment]
Great idea! I had the need for this as well but just stopped the null-ls LSP or set the filetype to "text" 😆 

Now, you can use `<leader>lf` to toggle autoformatting on save on and off for the current session. Default at start is on
