### ISSUE TITLE
How do you perform project wide search & replaces?

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#13]
1. Would be much appreciated to learn how you perform project wide search & replaces.
2. Also certain actions seem to change the project/workspace(?) to a subfolder of the actual area I'd like to work in, how can I set the permanent project workspace root to the location of the .git/ folder?
3. Bonus question, do you use anything to emphasize the active pane? I found https://github.com/jceb/blinds.nvim but it throws a segfault 

(lost some of these commands when I lost my previous dotfiles)

Thank you again for this amazing repo. It has been immensely helpful for me.

Using your Dockerfile on macOs

Update:
`rg foo --files-with-matches | xargs sed -i 's/foo/bar/g'` (gnu)
`rg foo --files-with-matches | xargs sed -i '' 's/foo/bar/g'` (mac)
seems like a reasonable solution, maybe we should bring it into vim?

**Comment by Allaman** [comment]
1) I usually do it the "vim" way via quickfix list (or location list). I load my files where I need to replace stuff either via `:grep` or via telescope (marking items with `TAB` and sending them to the quickfix list with `ctrl-q`. Then I can do my search and replace with `:cdo`. [Here](https://freshman.tech/vim-quickfix-and-location-list/) is a blog post that explains that in more detail

2) This is handled by project.nvim I guess. To test this you can comment out this plugin in `plugins.lua` and check if this behavior still occurs. Project.nvim sets the project root based upon [these settings](https://github.com/Allaman/nvim/blob/main/lua/config/project.lua). So if you have a nested structure this behavior can occur.

3) There was no need for me for this yet. The active pane (with my config) is indirectly emphasized via the active line highlight and the cursor.

glad that my config is helpful! 😄 

edit:
1) maybe [FAR](https://github.com/brooth/far.vim) is for you (not lua ^^)
