### ISSUE TITLE
mini.nvim statusline is set too low when using tmux

### ISSUE THREAD

**Issue by angelus2014** [Allaman/nvim#16]
Hello,

Trying out your Neovim configuration and I've noticed that the mini.nvim statusline overlaps with the tmux statusline. See the attached screenshot.
<img width="712" alt="Screenshot 2022-08-30 at 18 56 10" src="https://user-images.githubusercontent.com/7578963/187484236-e4cdd040-e17b-4e1c-b6a2-5867861ccb6e.png">

---
With regards,

Angelo Machils

**Comment by Allaman** [comment]
Hello,

Please check your tmux config as described in the responsible plugin [vim-tpipeline](https://github.com/vimpostor/vim-tpipeline#installation). I think your are especially missing the `status-justify "centre"` part

Best regards,
Michael

**Comment by Allaman** [comment]
side note: locally, I went back from mini statusline to lualine. When the testing is successful I will push the changes

**Comment by angelus2014** [comment]
Thank you!

**Comment by Allaman** [comment]
I added an [option](https://github.com/Allaman/nvim/blob/main/lua/user-conf.lua#L27) to disable the Tmux integration 
@angelus2014
