### ISSUE TITLE
Mac installation instructions

### ISSUE THREAD

**Issue by irl-segfault** [Allaman/nvim#19]
Hi there!  I tried out your config via the Dockerfile, and I really like it.  I'm not having success in getting things working natively on my Mac.  I'm not a poweruser of Neovim/lua, so probably a bit out of my depth here, but figured I'd open this issue in case I'm missing clear set up instructions that exist somewhere.

Thx for the work on this!  Really nice set up.

**Comment by Allaman** [comment]
Hi, glad that you like it!

There are no dedicated instructions for macOS. Basically it is just install [required](https://github.com/Allaman/nvim/#requirements) packages and clone this repo. 

You can have a look at the [install.sh](https://github.com/Allaman/nvim/blob/main/install.sh) script (which works only for some Linux based systems for now).  This script installs everything needed on a fresh Linux system. 
Especially, I think what [those](https://github.com/Allaman/nvim/blob/main/install.sh#L151-L153) functions do is interesting for you
