### ISSUE TITLE
'telegraph' not found

### ISSUE THREAD

**Issue by dev4mobile** [Allaman/nvim#2]
hello, I used your nvim configuration file,  but when  I execute `PackerSync` and then restart nvim, the following error is report, I'm using this config on my macos.
![image](https://user-images.githubusercontent.com/6851386/170448502-07faad80-2549-4b16-b04e-868713e0f3b0.png)

**Comment by Allaman** [comment]
hello, looks like a mistake in the config which should be fixed by https://github.com/Allaman/nvim/commit/25ea5391e57cf349ae65114868b4de2a13052b4c 
Thanks for pointing out!
