### ISSUE TITLE
Neogit not working after fresh clone of repo

### ISSUE THREAD

**Issue by kristiankupsch** [Allaman/nvim#24]
After a pull today Neogit isn't working anymore. 
I get "Not an editor command: Neogit"
I tried to manually load it in Packer but with no success.
Does anyone have any ideas what's going on?
Other git features work.
PackerStatus shows neogit as an installed plugin

**Comment by Allaman** [comment]
Tanks for reporting!
I can confirm this with my Docker image. My local nvim does not have this issue. 
I will dig into it later

**Comment by Allaman** [comment]
@kristiankupsch which version of Neovim are you running?

**Comment by kristiankupsch** [comment]
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

**Comment by kristiankupsch** [comment]
Updated to:
NVIM v0.9.0-dev-1378+ga8d454816-dirty
Build type: Release
LuaJIT 2.1.0-beta3

Error still occurs

**Comment by Allaman** [comment]
Thanks for the info

I found an issue in in [Neogit](https://github.com/TimUntersberger/neogit/issues/379) which I guess is the root cause

**Comment by kristiankupsch** [comment]
FYI Here is the PR that will fix it. Just in case you want to track it:
https://github.com/TimUntersberger/neogit/pull/380

**Comment by Allaman** [comment]
thanks!

**Comment by kristiankupsch** [comment]
FYI: The PR in Neogit is merged

**Comment by Allaman** [comment]
Yeah I saw it. Do you think https://github.com/Allaman/nvim/commit/092244719dfde6f670f69ff6d636b9858ec3c01e should be reverted. Actually, I like the workaround more than the original 😆

**Comment by kristiankupsch** [comment]
Well, I reverted it so see if (somehow magically) it solves the issue with color highlighting on OS X which is still not working correctly.
It doesn't. So I think leave it as is. Calling the Lua function directly seems less error prone.
