### ISSUE TITLE
can't delete file in mac os

### ISSUE THREAD

**Issue by dev4mobile** [Allaman/nvim#26]
I press `d`  commad to delete file,  there are some errors.
I use macos development environment.

![image](https://user-images.githubusercontent.com/6851386/203801371-4d048929-fbdf-4271-8e9b-434e2a189fd0.png)

**Comment by Allaman** [comment]
you are missing the tool [trash-cli](https://github.com/andreafrancia/trash-cli) which is [defined](https://github.com/Allaman/nvim/blob/main/lua/config/ui/neotree.lua#L257) as delete command. (like "move to bin" just for the command line)
