### ISSUE TITLE
Sharing my fork of your repo in case some changes might be useful to you

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#28]
https://github.com/Allaman/nvim/compare/main...partounian:nvim:main

Changes that I think you'd be most interested in:
- mini.comment support for multiple languages in a file (notably tsx, tsx, other templating languages)
- a few more treesitter libraries

----

update:

Also these seem cool
- https://github.com/mfussenegger/nvim-treehopper
- https://github.com/lewis6991/impatient.nvim

**Comment by Allaman** [comment]
Hi @partounian, 
apologies for my delayed response! I will have a look at your config. As you might see, my config evolved as well 😆 

I knew of both plugins, but I had no use case for treehopper and the impact of impatient was barely measurable. 

As I moved from packer to lazy, I do not care that much anymore and let lazy handle the loading with its magic

**Comment by Allaman** [comment]
Hi @partounian 
What does `nvim-treesitter/nvim-treesitter-context` do? I installed it and nothing happens 😆

**Comment by partounian** [comment]
You use it with mini.comment to correct use comments for filetypes like JSX/TSX. https://github.com/Allaman/nvim/compare/main...partounian:nvim:main#diff-4a5cfe72d46e1123cc73f5d2e3235f3c9af00ca36a3c58132aacde11fdb97069 

@Allaman

**Comment by Allaman** [comment]
@partounian Ahh I see! Thanks for clarification!
