### ISSUE TITLE
Neotree not loading. Go files not triggering code section

### ISSUE THREAD

**Issue by kristiankupsch** [Allaman/nvim#29]
Hi it's me again.
With a clean install Neotree doesn't open by default. After :PackerLoad neo-tree.git it works.
Second: When editing a go file, the lsp doesnt seem to work. coding section after pressing leader key is not available.
When opening a go file I get the following warning: "gopls not found", "Setup called twice"

I tried to figure out where the setup is called a second but wasn't successful

**Comment by kristiankupsch** [comment]
Install was made with your install script

**Comment by Allaman** [comment]
Hi,

I guess you mean neo-tree as a netrw replacement? Due to packer loading neotree only after a [Neotree command](https://github.com/Allaman/nvim/blob/main/lua/plugins.lua#L241) it is not loaded in a freshly started Neovim instance.

Did you verify if gopls is available in your path? Did the script return any errors?

**Comment by j33pguy** [comment]
Hi all, 
*love the config, has given me lots of inspiration

So I started running into this same issue...Playing around and looking into :PackerStatus, I noticed that Neotree was not started, even with the cmd: NeoTree*.  

Removing that command line, Neotree is now started...

Looks like there was a release update on Neotree 3 weeks ago that broke this or something....looking into fix...will post here if I find anything..

**Comment by Allaman** [comment]
Hi @j33pguy, thanks for your feedback! I am pleased that my config gives you inspiration

I can not confirm this. Here is what I have done:

1. start Neovim
2. run `PackerStatus` -> neo-tree is "not-loaded"
3. `<leader>fp (mapping for `Neotree reveal toggle`) 
4. run `PackerStatus` -> neo-tree "not-loaded" is gone

**Comment by j33pguy** [comment]
Thanks for quick reply....so running through same commands Neotree is not showing up at all...cannot run things through cmd :Neotree xxxxx either

**Comment by j33pguy** [comment]
Looking at Neo-tree docs.....they list breaking changes past 1.3 should not be an issue...and specifically list NeoTree* for highlighting !?!?!

right link:
https://github.com/nvim-neo-tree/neo-tree.nvim#what-is-a-breaking-change

wrong link
~~https://github.com/nvim-neo-tree/neo-tree.nvim/issues/186~~

**Comment by j33pguy** [comment]
Whats interesting is removing the cmd = "NeoTree*" line moves where packer is placing file from /local/nvim/xxxx/xxx/opt to /xxxx/xxxx/start which is why it was auto starting

**Comment by Allaman** [comment]
Sorry, I don't get it. Your link refers how a breaking change for neo-tree is defined, but noch an actual breaking change?

> line moves where packer is placing file from /local/nvim/xxxx/xxx/opt to /xxxx/xxxx/start which is why it was auto starting

This is as intendend. The `cmd` option of packer is for lazy loading (placing packages in the `opt` path). My Intention there is, that neo-tree should be lazy loaded only when I run the command. This is also the reason why neo-tree does not replace netrw when opening a directory on startup.

Nevertheless, I just recognized that the command is misspelled. https://github.com/Allaman/nvim/commit/226d510248bfcf9a199b29d1397ad41fef53bf15

**Comment by j33pguy** [comment]
OK.....so found my issue...Telescope was not loaded....after running :Telescope I was able to run things with your spelling change to Neotree*

**Comment by Allaman** [comment]
Great!
