### ISSUE TITLE
Rework LSP + Mason setup

### ISSUE THREAD

**Issue by Allaman** [Allaman/nvim#37]
Mason and lsp-config are separated though there exists mason-lspconfig.

Goal should be to spefiy LSPs in one place and Mason ensures that the LSPs are installed and mason-lspconfig wires the setting

https://github.com/williamboman/mason.nvim
https://github.com/williamboman/mason-lspconfig.nvim

**Comment by flamedmg** [comment]
Any plans to switch to LazyVim ? i found that your and lazyvim default config are close, so possibly switching to lazyvim will save you time configuring routine stuff like lsp  / treesitter etc

**Comment by Allaman** [comment]
Hi @flamedmg, I have no plans to switch to LazyVim. Of course, I do like LazyVim, as pretty much all of @folke's stuff, but I also like running my config with all its ups (and downs) ;)
Thanks for your hint!

**Comment by Allaman** [comment]
solved
