### ISSUE TITLE
How can I disable/adjust the transparency for the completion popup?

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#39]
I've tried searching through the cmp, lsp, settings and theme files but couldn't find it.

**Comment by flamedmg** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/416393/216249935-145884db-01cd-4739-ae12-1843760081d6.png">
Then you can see options available here: https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/config/window.lua

**Comment by flamedmg** [comment]
Looks like it doesn't answer your question...

**Comment by Allaman** [comment]
Have a look at `:h pumblend` and `:hi Pmenu`. These should control the popup menu

**Comment by Allaman** [comment]
@partounian can we close the issue? I am not aware of a cmp option that does control this. As said in my previous post, the only way I am aware of is to tweak Neovim's popup menu.

**Comment by partounian** [comment]
> @partounian can we close the issue? I am not aware of a cmp option that does control this. As said in my previous post, the only way I am aware of is to tweak Neovim's popup menu. 

Yes definitely. I just remember the popup behaving differently last year in this repo, so thought maybe it was a specific configuration setting you knew.

**Comment by partounian** [comment]
For anyone who comes across this, the answer was setting pumblend to 0. Ideally I could use low values, but even 1 and 2 seems too transparent.
