### ISSUE TITLE
By chance has anyone gotten copilot working properly with this config?

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#44]
I've tried many things, but the lua versions of copilot don't work. I'm only able to get it partially working with https://github.com/hrsh7th/cmp-copilot .

I tried following putting the config directly into [cmp.lua](https://github.com/Allaman/nvim/blob/main/lua/core/plugins/cmp.lua), and also tried copying [the copilot file from LazyVim](https://www.lazyvim.org/plugins/extras/coding.copilot 
) with some adjustments without luck 
https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/coding/copilot.lua put that file into a new folder `lua/plugins` then changed the lazy.setup to

commit of my latest attempt to get it working https://github.com/partounian/nvim/commit/31984f85a8ed29308f4f1c673e45415de0bf235b

```
require("lazy").setup({
  spec = {
  { import = "core.plugins" },
  { import = "plugins" },
  },
  -- defaults = { lazy = true },
  install = {
    -- install missing plugins on startup. This doesn't increase startup time.
    missing = true,
  },
  change_detection = {
    -- automatically check for config file changes and reload the ui
    enabled = false,
    notify = true, -- get a notification when changes are found
  },
  debug = false,
})
```

**Comment by Allaman** [comment]
Unfortunately, I do not have a Copilot subscription :(

**Comment by partounian** [comment]
Haven't had to chance to revisit again but I think the answer will be here

https://github.com/matthewsia98/dotfiles/blob/main/nvim/.config/nvim/lua/plugins/completion/copilot.lua
https://github.com/matthewsia98/dotfiles/blob/main/nvim/.config/nvim/lua/plugins/completion/init.lua

**Comment by Allaman** [comment]
Hi @partounian 

just a small note regarding this assumption:
> I tried adapting the copilot logic in this repo for https://github.com/Allaman/nvim which I believe was based on LazyVim, however whatever I tried made nvim-cmp not show any results.

My setup is not based upon LazyVim, but it's an honor that my effort apparently wasn't so wrong. If it would be based on LazyVim, then it would probably work 😆

**Comment by Allaman** [comment]
Hi @partounian 

FYI https://github.com/Allaman/nvim/commit/0ef8f561d817dd085108b65982c307bb7749befb 😆

**Comment by partounian** [comment]
You are my favorite software engineer 🙌🏼
