### ISSUE TITLE
dap with go issues (doesn't seem to actually attach to the process?)

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#46]
Does it work for you?

It doesn't seem to actually attach to the process, but I'm able to attach to it in GoLand, so that's leading me to believe it could be something with the nvim config. Also, if it does connect how would I use/navigate to the icons like the pause, play, step over etc. I tried looking for the docs but couldn't find clear info on the dap-ui. 

Thanks again!

**Comment by Allaman** [comment]
Yes, it does, but I barely use it. I mostly use step into|over|out commands and nothing more.

![dap](https://github.com/Allaman/nvim/assets/12184268/64f678cc-4856-4dd8-b47f-750b662ad5a2)
