### ISSUE TITLE
Allaman in the Lazyman Neovim Configuration Manager

### ISSUE THREAD

**Issue by doctorfree** [Allaman/nvim#47]
I'm working on including this configuration in [Lazyman](https://github.com/doctorfree/nvim-lazyman), a Neovim configuration manager.

In order to get this config to initialize cleanly with `nvim --headless "+Lazy! sync" +qa` it was necessary to patch `mason.lua` slightly to refresh the registry. Not sure why. Below is the patch I am using.

If you have any concerns, questions, comments, or suggestions as to how best to incorporate this configuration into `Lazyman` please feel free to fire away. It was one of the Neovim configs that motivated and inspired me to write a configuration manager. Your `install.sh` script acted as a template for the Lazyman [install_neovim.sh](https://github.com/doctorfree/nvim-lazyman/blob/main/scripts/install_neovim.sh) although it has since diverged quite a bit. I kept your copyright notice intact, let me know if you want me to remove it.

I also based a lot of my own configuration off of some of what you have done, especially your `settings.lua` so thanks all around!

After patching (during the initial installation prior to initialization) the 'Allaman' Neovim configuration works well and I am planning on including it in the next release (v2.1.4r4).

`mason.lua` patch:

```
--- lua/core/plugins/mason.lua.orig	2023-06-05 18:56:59.153237963 -0700
+++ lua/core/plugins/mason.lua	2023-06-05 18:59:38.646269035 -0700
@@ -11,12 +11,19 @@
 
     -- ensure tools (except LSPs) are installed
     local mr = require("mason-registry")
-    for _, tool in ipairs(settings.tools) do
-      local p = mr.get_package(tool)
-      if not p:is_installed() then
-        p:install()
+    local function install_ensured()
+      for _, tool in ipairs(settings.tools) do
+        local p = mr.get_package(tool)
+        if not p:is_installed() then
+          p:install()
+        end
       end
     end
+    if mr.refresh then
+      mr.refresh(install_ensured)
+    else
+      install_ensured()
+    end
 
     -- install LSPs
     require("mason-lspconfig").setup({ ensure_installed = settings.lsp_servers })
```

**Comment by Allaman** [comment]
Hello @doctorfree,

Thank you for your warm words. I am glad that you like my config and that it gives you inspiration. 

I will definitely take a look at Lazyman! It's crazy what drive the Neovim community develops after the introduction of Lua as a first class citizen. :)

I have no concerns nor any questions regarding your integration of my config. Please don't hesitate to integrate it as you like.

Furthermore, thanks for the patch!

**Comment by Allaman** [comment]
Implemented https://lazyman.dev/info/Allaman.html :)

Thanks!
