### ISSUE TITLE
Suggestion for an easier git mergetool 

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#50]
Maybe my head is special, but I always forget or have janky behavior with mergetools in nvim or going back in git blames via nvim.

This plugin is so easy to use, one might even call it the only intuitive nvim git mergetool xD https://github.com/akinsho/git-conflict.nvim

**Comment by Allaman** [comment]
Hi @partounian, thanks for your suggestion. Always appreciated! 
I will take a look at it. Merging is something I struggle in Neovim a little too.

**Comment by Allaman** [comment]
@partounian Do you have an opinion on how git-conflict.nvim compares to diffview.nvim (which has more feautures)?

**Comment by partounian** [comment]
git-conflict.nvim is easy and runs inline basically. Just hit `ct` or `co` for any conflict and you're good. If it's a more complex conflict you are trying to solve, maybe diffview.nvim separated view might be more helpful

**Comment by Allaman** [comment]
@partounian I decided to introduce a user setting to choose which tool to use 
What's your opinion on this solution?

**Comment by partounian** [comment]
Since diffview was lazy loaded by waiting for commands like `DiffviewOpen`, I didn't see a reason to not leave both on my system for now, but yeah I don't think both will realistically be necessary so your solution is nice.

**Comment by Allaman** [comment]
@partounian I added the option to use both plugins

**Comment by partounian** [comment]
Oh nice, I've been doing the same! :) https://github.com/partounian/nvim/commit/62f94b1e3bef291498e0f453932a2f21dfbc57a3 

I probably should've made a PR, but for some reason I didn't think you'd be interested

**Comment by Allaman** [comment]
Haha, I promise I was no copycat 😆
