### ISSUE TITLE
Lua error citing treesitter/highlighter while using golang

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#52]
![screenshot](https://github.com/Allaman/nvim/assets/26134018/7be11fe7-b658-4216-ad66-dc8f20e7efe3)

nvim --version
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by Allaman** [comment]
Did you run `TSUpdate go`?
What does `:checkhealth nvim-treesitter` say?

**Comment by aphsa** [comment]
Parsers are up-to-date for nvim-treesitter.

For checkhealth, I got the following.

```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.15.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-46-generic",
  sysname = "Linux",
  version = "#47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2"
} 
```
I was able to install the tree-sitter cli using cargo and that didn't fix the error message as in the screenshot submitted earlier.

**Comment by Allaman** [comment]
The nvim-treesitter healthcheck tells you that all go features are enabled?
<img width="354" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/07aad007-37c8-4282-be98-abdffee9a81b">

Could you provide a minimal go snippet, that leads to the error?

> I was able to install the tree-sitter cli using cargo and that didn't fix the error message as in the screenshot submitted earlier.

I am not aware of such a CLI and it should work without it

**Comment by aphsa** [comment]
I removed  snap package neovim installed a unstable version from a ppa.

```sh
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim

nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
That fixed the issue.
