### ISSUE TITLE
Fuzzy file finding (<leader>ff) stopped working with the recent fzf changes

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#55]
When using `<leader>ff` fuzzy finding

https://github.com/Allaman/nvim/commit/5e973ed152f4a687401fc662ec6f826430235221#diff-fc8606d73d1acc1b165a5a5783e84f27f330d8496bb3ae6ccc1cacd15f82199b

**Comment by Allaman** [comment]
Hi @partounian, have you checked the output of `:checkhealth core`? I am excited if it would give us any hint :laughing: 

I just built the nvim Docker image with my config and cannot reproduce the error. I assume that on your system `fzf` (the [original](https://github.com/junegunn/fzf)) is missing.

Background for my decision to remove telescope-fzf-native.nvim: 
The plugin requires gcc / build tools to be able to build, which is just too much bloat in my opinion. In addition, fzf (the original one) is a tool I very much rely on and is always installed by my package managers (brew, pacman, ...). I personally cannot justify the gcc dependency with an increase in speed in comparison to the original fzf (written in Go, a rather performant language as well)

**Comment by partounian** [comment]
Yes, `:checkhealth core` reports everything is OK except for missing `skim`.

Interesting that it doesn't work for me. I can search files, but the fuzzy part is not working. I will run your docker image again later to verify

**Comment by Allaman** [comment]
Maybe our expectation are different. fzf-native comes with another algorithm, I think.

Here is a screenshot within this repo's directory. Are the results different for you?

<img width="1115" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/4f13453d-1dd4-47f2-995b-c1d30975c333">

**Comment by partounian** [comment]
Those results are the same. You're right that our expectations are different. For example, I expect to see when results when I type `lua cmp`.

**Comment by Allaman** [comment]
Hmm, I'm uncertain if a space in the search term is "valid"? Without space I see proper results.
<img width="1102" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/68e6c30c-9c4d-422d-a524-c10769d2b06c">

**Comment by Allaman** [comment]
I think a space is interpreted as, well ,space 😆 
<img width="176" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/865ab89d-be34-450e-923e-757f27099672">
<img width="1098" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/97d52cc3-bab6-486f-8898-6cdef73feb06">
Note the missing `foobar.lua` in the results

**Comment by Allaman** [comment]
Good news @partounian 😄 https://github.com/Allaman/nvim/commit/e799041d2648a416851c53575aa9bc2bc81c3f83

With just `telescope.load_extension("fzf")` the sorters should be overwritten and the other stuff I deleted in https://github.com/Allaman/nvim/commit/5e973ed152f4a687401fc662ec6f826430235221 should not be necessary

`config.lua`

```lua
return {
  plugins = {
    telescope = {
      fzf_native = {
        enable = true,
      },
    },
  },
}
```
