### ISSUE TITLE
Cool package for project wide search & replace

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#56]
https://github.com/nvim-pack/nvim-spectre

**Comment by Allaman** [comment]
Hi @partounian,
I know this plugin but never wanted to use it, as it differs a lot to the "vim way". But to be honest, it is way more convenient than the built-in search and replace :)
I added a toggle to enable/disable the plugin.

**Comment by Allaman** [comment]
With https://github.com/Allaman/nvim/issues/57 a `config.lua`snippet that enables this plugin looks like 

```lua
return {
  plugins = {
    spectre = {
      enable = true,
    },
  },
}
```
