### ISSUE TITLE
can not c open file in the file browser by mouse click

### ISSUE THREAD

**Issue by turbo2025** [Allaman/nvim#59]
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

nvim config is last in main branch

errore message:

E5108: Error executing lua: ...lazy/nvim-window-picker/lua/window-picker/configurer.lua:49: attempt to index field 'unfocused' (a nil value)
stack traceback:
        ...lazy/nvim-window-picker/lua/window-picker/configurer.lua:49: in function '_backward_compatibility_config_changes'
        ...lazy/nvim-window-picker/lua/window-picker/configurer.lua:6: in function 'new'
        ...im/lazy/nvim-window-picker/lua/window-picker/builder.lua:40: in function 'build'
        .../nvim/lazy/nvim-window-picker/lua/window-picker/init.lua:37: in function 'pick_window'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:710: in function 'open_file'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:562: in function 'open'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:595: in function 'open_with_cmd'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:726: in function 'open_with_window_picker'
        ...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:203: in function 'func'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:830: in function <...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:828>

**Comment by turbo2025** [comment]
systemc info：
OS: Manjaro Linux x86_64 
Kernel: 6.5.0-1-MANJARO 

your nvim config is awasome by the way ：）

**Comment by Allaman** [comment]
Hi @turbochoo,
thanks for your feedback. A slight error in my window-picker config has crept in. It should be fixed now :)

> your nvim config is awasome by the way ：）

Glad that you like it 👍 


edit: That's not the issue... looking further

**Comment by Allaman** [comment]
BTW, this was the first time I used my mouse in Neovim 😆

**Comment by Allaman** [comment]
Ok, please test now :)

**Comment by turbo2025** [comment]
thanks, man ,it work :) @Allaman
