### ISSUE TITLE
Live grep slow with specific repositories

### ISSUE THREAD

**Issue by afterlook** [Allaman/nvim#6]
I noticed when under specific repositories live grep can be unusually slow or even non responsive.

How to reproduce:
1. clone https://github.com/kumahq/kuma
2. open nvim in kuma
3. Telescope live_grep for `Duration`

**Comment by Allaman** [comment]
Unfortunately, I cannot reproduce this

https://user-images.githubusercontent.com/12184268/174885818-7488bf52-975a-4315-9dce-9be47e099698.mp4

Do you have the tools installed listed in the [tools](https://github.com/Allaman/nvim#tools) section?

**Comment by afterlook** [comment]
Yeah I do. 

There is a possibility that this is isolated to my environment. I'm just trying to confirm before I deep dive.

In response to you trying to reproduce this - the way you do things, I'm also not getting any stutters. The problem starts occurring when a file/buffer is opened. Sorry for not including video before.

https://user-images.githubusercontent.com/29754364/174894191-805f1060-29c5-4046-b3b0-0c067552d496.mp4

**Comment by Allaman** [comment]
Unfortunately for me ;),  I can reproduce this behavior while a file is opened...

Maybe you add this to your issue [here](https://github.com/nvim-telescope/telescope.nvim/issues/2008) as well?

I will also try to figure out whats going on

**Comment by Allaman** [comment]
Removing nvim-telescope/telescope-fzf-native.nvim or nvim-telescope/telescope-ui-select.nvim shows no effect (as expected^^)

**Comment by afterlook** [comment]
Yeah, I tried to play a little bit before i wrote this issue here. Using basic telescope configuration, removing/changing plugins that have an effect on telescope live_grep, but couldn't solve this in any way.

**Comment by afterlook** [comment]
And regarding nvim-telescope/telescope.nvim#2008, I closed the issue - made a mistake and did not open nvim with completely minimal config. It's not telescope fault, something other is interacting causing stutters/slowdowns.

**Comment by Allaman** [comment]
there is a c/p error with your link in your last comment ;)

**Comment by Allaman** [comment]
also occurs on my Intel amd64 Arch Linux machine

**Comment by Allaman** [comment]
Hi, before I dig deeper can you please comment out and let Packer remove the [colorizer](https://github.com/Allaman/nvim/blob/main/lua/plugins.lua#L68) plugin and then test again? My tests show that this plugin is the root cause of the lag

**Comment by afterlook** [comment]
Yeah, that does the trick. Thanks!

**Comment by Allaman** [comment]
Thanks for your help

I removed colorizer for now. I am not aware of any Lua alternatives so maybe I add [vim-hexokinase](https://github.com/RRethy/vim-hexokinase) in the future

**Comment by partounian** [comment]
For anyone else still using fzf, it seems that disabling override_generic_sorter in the telescope fzf module settings fixes the slow live grep issue even though grepping still isn't perfect and seems to be searching fixes it should be ignoring.
