### ISSUE TITLE
Request: Documentation to  enable copilot

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#61]
How to enable copilot?

**Comment by Allaman** [comment]
Hi @aphsa, Copilot must be enabled in your [user configuration](https://github.com/Allaman/nvim#user-configuration). 

So in your case, you need the following snippet in your `.nvim_config.lua`

```lua
return {
  plugins = {
    copilot = {
      enable = true,
    },
  },
}
```

After the installation, Lazy should automatically run `:Copilot auth` and you must provide your authentication

**Comment by aphsa** [comment]
E492: Not an editor command: Copilot auth

**Comment by aphsa** [comment]
I end reinstalling from scratch after removing .config/nvim and .local/share/nvim and that resolved the issue.
