### ISSUE TITLE
What keybinding to accept copilot suggestion?

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#66]
What keybinding should be used  to accept copilot suggestion when in python mode?
Tab is not working for me.

**Comment by Allaman** [comment]
You should use tab to select the suggestion from Copilot and then hit enter to insert it

**Comment by aphsa** [comment]
Tab under the Python "for" statement , inserts a tab. It does not select the suggestion. When i press enter , it creates a newline.

**Comment by Allaman** [comment]
This is how it should look.  I need to enable Copilot first, as it is off in my config (I have overwritten [autostart](https://github.com/Allaman/nvim/blob/main/lua/core/config/defaults.lua#L78) in my user-specific config file). 

After the copilot suggestion pops up, I hit tab to select it and enter to insert it

![copilot](https://github.com/Allaman/nvim/assets/12184268/23e2a3b4-c4d3-4fe1-b244-0e6c5e0d1609)

**Comment by aphsa** [comment]
What you showed me up there works for me too until line 13 (in this example) where tab doesn't highlight the copilot recommendation anymore and only keeps on moving the cursor forward on line 13.
```
   4 def Summary():
    3 │   """dfsdfsd"""
    2 │   for line in run_command("journalctl --disk-usage"):
    1 │   │   if line.startswith("Archived and active journals take up"):
  13  │   │   │   │   │
    1 │   │   │   liner= line.replace("...1ls take up", "")  Copilot
    2 │   │
    3 │
```

**Comment by Allaman** [comment]
You config include my latest commits, including the configuration for cmp?
Can you provide a minimal not working example of Python code, or does Copilot auto-completion in general not work?

**Comment by aphsa** [comment]
Yes i have the latest commit. Does this python screenshot help.

![2023-10-09-163451_3840x2160_scrot](https://github.com/Allaman/nvim/assets/26134018/bbaa6afa-8baf-415f-8bf9-cf2202011aec)

I am not able to tab into  that copilot suggestion. See that in the screenshot?

**Comment by partounian** [comment]
I haven't had an issue with Copilot on my side either.

I can test on my machine as well, if you wanna share your python script & config for this repo. Have you made any changes to this repo?

**Comment by aphsa** [comment]
I didn't make any changes to this repo. In fact I deleted my existing config and git cloned a the latest version.

I should have given the code before. But look for the python script here -> https://github.com/aphsa/copilottest.git
Go to line 81 and try to add the copilot suggestion and let me know if you have the same issue.

**Comment by Allaman** [comment]
sry, I can't reproduce it with your code either :(

![copilot](https://github.com/Allaman/nvim/assets/12184268/1bf60024-4c7f-449c-bc68-e03eaf276e5f)

@partounian Could you take a look at the provided code as well please?

**Comment by aphsa** [comment]
Try not typing "if" and wait for the copilot recommendation

**Comment by partounian** [comment]
If there is nothing typed, I do see the behavior of just the cursor moving forward rather than accepting the autocomplete.

**Comment by partounian** [comment]
@aphsa is there any issue for you, if you type `if` then accept that recommendation?

**Comment by aphsa** [comment]
If I type the "if" the recommendation applies after tabbing. Like you said above,  if I don't type "if",  the cursor spaces forward after tabbing instead of applying the copilot recommendation.  I want to know if that is normal?

**Comment by partounian** [comment]
I believe it is normal behavior. If you remove the `has_words_before` here it might change that behavior

**Comment by aphsa** [comment]
> I believe it is normal behavior. If you remove the `has_words_before` here it might change that behavior

That worked. Thank you

**Comment by Allaman** [comment]
thanks @partounian 

I can't figure it out why I added the `has_words_before` :/ I guess it was an issue with snippets and cmp, but I am not sure.

**Comment by partounian** [comment]
@Allaman it was a recommendation by one of the copilot plugins, I recall doing the same.
