### ISSUE TITLE
Which version of neovim are you using exactly?

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#69]
Recent ightly builds have been crashing a lot for me. I've been trying different builds for the past couple of weeks.

**Comment by Allaman** [comment]
I am running `NVIM v0.10.0-dev-2656+g6823fdb20-Homebrew` without crashes.

I must admit that I barely update Neovim itself 🙈

**Comment by partounian** [comment]
g6823fdb20 is not the commit hash right? it doesn't seem to be when I try https://github.com/neovim/neovim/commit/g6823fdb20 
where as https://github.com/neovim/neovim/commit/1094d0c0dbd0f37ccc0f1d18c73c6066e5690664 and randomly abbreviated https://github.com/neovim/neovim/commit/1094d0c0 works

**Comment by Allaman** [comment]
I don't know what this stands for :/ 
It is the output from `neovim --version`. Maybe something brew specific...

Perhaps this helps:
<img width="781" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/8dac76dc-4ca3-4214-a81f-ee71c896df30">
This resolves to a commit hash: https://github.com/neovim/neovim/commit/6823fdb

**Comment by partounian** [comment]
Thanks!
