### ISSUE TITLE
Golang colorscheme 

### ISSUE THREAD

**Issue by hwnprsd** [Allaman/nvim#7]
I'm using the same colorscheme (catpuccin) with the exact same config as you. My go code looks pale with minimal syntax highlighting. Can you help me resolve this?

<img width="649" alt="image" src="https://user-images.githubusercontent.com/23007190/179354896-0872615d-8dc9-4471-a5cb-deaaac247417.png">

**Comment by Allaman** [comment]
hmm Treesitter parsers are installed? 
Does `:checkhealth` return any issues?
Does your Terminal display all colors? `for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""`

**Comment by hwnprsd** [comment]
So I did manage to fix it by using more of your configuration. I'm stuck with Rust not having enough colors now. 
I have installed the LSP for Rust. How should I approach this problem for other languages?

**Comment by Allaman** [comment]
Did you add "rust" to the enabled treesitter languages?
https://github.com/Allaman/nvim/blob/main/lua/config/treesitter.lua#L2

**Comment by Allaman** [comment]
closed due to inactivity
