### ISSUE TITLE
start nvim and show null-ls fail run message

### ISSUE THREAD

**Issue by turbo2025** [Allaman/nvim#71]
[null-ls] failed to run generator: ...im/lazy/none-ls.nvim/lua/null-ls/helpers/diagnostics.lua:71: index out of range

nvim config is latest

my system infomation:

Manjaro Linux x86_64 
Kernel: 6.1.66-1-MANJARO 
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742

**Comment by turbochoo** [comment]
above issue in  my python project  when use nvim

**Comment by turbo2025** [comment]
> [null-ls] failed to run generator: ...im/lazy/none-ls.nvim/lua/null-ls/helpers/diagnostics.lua:71: index out of range
> 
> nvim config is latest
> 
> my system infomation:
> 
> Manjaro Linux x86_64 Kernel: 6.1.66-1-MANJARO NVIM v0.9.4 Build type: Release LuaJIT 2.1.1702233742
only my venv  path error in pyrightconfig.json

**Comment by Allaman** [comment]
Please provide a minimal example in what scenario this error occurs

**Comment by turbo2025** [comment]
> Please provide a minimal example in what scenario this error occurs

The warning message show in the main window. after  run nvim command in the terminal.

**Comment by Allaman** [comment]
You are not running the latest version as null-ls was replaced [here](https://github.com/Allaman/nvim/commit/78b610ea7a22bd09e9ee8cb9bc9020f69d7e6976)

**Comment by Allaman** [comment]
Didn't read the error message properly...

However, if you can't provide a minimal not working config i cannot do much. There is no such error in my local nvim and my Docker image containing the same configuration.

Have you read https://github.com/nvimtools/none-ls.nvim/tree/main#faq ?

Maybe my config is incompatible with Neovim 0.9 (anymore)
