### ISSUE TITLE
Config issues in fresh install

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#75]
Using Ubuntu 22.04 
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Getting the following error when trying to open go file.

``` Failed to run `config` for none-ls.nvim

/home/userj/.config/nvim/lua/core/plugins/lsp/none-ls.lua:15: attempt to index field 'latexindent' (a nil value)

# stacktrace:
  - ~/.config/nvim/lua/core/plugins/lsp/none-ls.lua:15
  - ~/.config/nvim/lua/core/plugins/none-ls.lua:8 _in_ **config**
  ```

**Comment by Allaman** [comment]
Hello, do you have [latexindent](https://github.com/cmhughes/latexindent.pl) installed? It is required by the [none-ls](https://github.com/Allaman/nvim/blob/main/lua/core/plugins/lsp/none-ls.lua#L15) config.
I am working on replacing none-ls, so this will be configurable in the future (i hope 😄 )

**Comment by partounian** [comment]
Can also just comment out the parts not relevant. I personally disabled the latex stuff

**Comment by aphsa** [comment]
I have latexindent and latexindent.PL  and eslint_d installed and in my path , but I still get the following error;

``` 
[null-ls] failed to load builtin eslint_d for method diagnostics; please check your config
[null-ls] failed to load builtin latexindent for method formatting; please check your config
Press ENTER or type command to continue
```

**Comment by Allaman** [comment]
Hello, I can't really tell how your system is configured, so I only see these options:

1. You disable the various failing builtins as @partounian suggested
2. You enable [debug output for none-ls](https://github.com/nvimtools/none-ls.nvim?tab=readme-ov-file#how-do-i-enable-debug-mode-and-get-debug-output) and check the logs if there are further hints
3. You are patient until I push my changes to replace none-ls which should give you the possibility (and responsibility) to configure linter (and formatter) yourself......

edit: `eslint_d` is installed by Mason.  It is on your system and path?

<img width="521" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/a36f9966-7b05-49bc-8c9c-4409302776c8">

**Comment by Allaman** [comment]
I just pushed some major rework.

- [Replacing none-ls with conform.nvim and nvim-lint](https://github.com/Allaman/nvim/commit/09634d22fcddadb954b74c2e14bb028a3ab39893)
- [Refactor default config structure](https://github.com/Allaman/nvim/commit/4b8b994a15f6842f4a54e5a6850cc6181719df39)

How may this affect you? As mentioned, this allows you to configure both formatting and linting via the user file. 

I wrote a default configuration for autoformatting[^1] and linting[^2] that should almost exactly match the previous none-ls setup. However, both configs can be overwritten and adjusted to your needs.

For instance, to change the formatter for Python from ruff to black you can add this snippet to your local .nvim_config.lua: 

```lua
  plugins = {
    conform = {
      opts = {
        formatters_by_ft = {
          python = { "isort", "black" },
        },
      },
    },
```

[^1]: https://github.com/Allaman/nvim/blob/main/lua/config/defaults/conform.lua
[^2]: https://github.com/Allaman/nvim/blob/main/lua/config/defaults/lint.lua

**Comment by aphsa** [comment]
Everything is back in place now. Thank you
