### ISSUE TITLE
Some filetype colors not being applied anymore (but is still visible in telescope?)

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#78]
I noticed with the latest changes that my Golang (yml, and maybe others as well) syntax isn't highlighted properly anymore. Seems like other filetypes are fine and in telescope preview the syntax colors are proper, but when I'm editing a go file the syntax is not properly colored.

**Comment by Allaman** [comment]
Hello @partounian ,

Thanks for reporting! I didn't even notice because I was so busy refactoring stuff 🤦 

This [commit](https://github.com/Allaman/nvim/commit/dc89affa908e578952e4a8df739c320d457d440a) should solve the problem.

No clue why this is not the default...
