### ISSUE TITLE
migrate to tenv from tfswitch

### ISSUE THREAD

**Issue by kvendingoldo** [Allaman/nvim#80]
Hi! I saw that you're using tfswitch. It does not support Terragrunt and OpenTofu, so, I suggest you to switch to tool that can manage all of these tools together: https://github.com/tofuutils/tenv

**Comment by Allaman** [comment]
Hello! Thanks for the hint. I had to grep over the repo to figure out where tfswitch is mentioned 😆 

The `install.sh` does not get much love, and I think that the provided Docker image is a better suited way of “installing” my config.
