### ISSUE TITLE
Getting these 3 errors in the fresh install

### ISSUE THREAD

**Issue by Patil-Kranti** [Allaman/nvim#81]
# Error 1 :-
Can not load user config: cannot open /Users/krantipatil/.nvim_config.lua: No such file or directory
Error detected while processing /Users/krantipatil/.config/nvim/init.lua:
Failed to load `core.plugins.telescope`

/Users/krantipatil/.config/nvim/lua/utils/functions.lua:69: attempt to index field 'telescope' (a nil value)

# stacktrace:
  - lua/utils/functions.lua:69 _in_ **project_files**
  - lua/core/plugins/telescope.lua:67
  - lua/config/lazy.lua:20
  - lua/config/init.lua:32 _in_ **init**
  - lua/config/init.lua:37
  - init.lua:3

# Error 2 :-
Failed to run `config` for catppuccin

...atil/.config/nvim/lua/core/plugins/themes/catppuccin.lua:13: attempt to index field 'harpoon' (a nil value)

# stacktrace:
  - lua/core/plugins/themes/catppuccin.lua:13
  - lua/core/plugins/theme.lua:39 _in_ **config**
  - lua/config/lazy.lua:20
  - lua/config/init.lua:32 _in_ **init**
  - lua/config/init.lua:37
  - init.lua:3

# Error 3 :-
Failed to run `config` for alpha-nvim

/Users/krantipatil/.config/nvim/lua/utils/functions.lua:69: attempt to index field 'telescope' (a nil value)

# stacktrace:
  - lua/utils/functions.lua:69 _in_ **project_files**
  - lua/core/plugins/alpha/alpha.lua:176
  - lua/core/plugins/alpha.lua:14 _in_ **config**

following is the result of :checkhealth.
System configuration ~
- OK This config will work with your Neovim version
- OK Running on supported OS: Darwin
- WARNING No or wrong (check :messages) user configuration provided (this is optional)
- OK 'go' executable found
- OK 'cargo' executable found
- OK 'node' executable found
- OK 'fd' executable found
- ERROR 'trash' executable not found - Neo-tree requires 'trash-cli' to be able to move files to the trash
- OK 'rg' executable found
- WARNING 'tectonic' executable not found - to compile LaTex files
- WARNING 'skim' executable not found - to view compiled LaTex files (PDFs)
- WARNING gsed was not found - nvim-spectre (search and replace) might not work
- ERROR Failed to run healthcheck for "core" plugin. Exception:
  /Users/krantipatil/.config/nvim/lua/core/health.lua:112: attempt to index field 'telescope' (a nil value)
  

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- ERROR Issues were reported when loading your specs:
- ERROR Failed to load `core.plugins.telescope`
- ERROR 
- ERROR /Users/krantipatil/.config/nvim/lua/utils/functions.lua:69: attempt to index field 'telescope' (a nil value)
- ERROR 
- ERROR # stacktrace:
- ERROR   - lua/utils/functions.lua:69 _in_ **project_files**
- ERROR   - lua/core/plugins/telescope.lua:67
- ERROR   - lua/config/lazy.lua:20
- ERROR   - lua/config/init.lua:32 _in_ **init**
- ERROR   - lua/config/init.lua:37
- ERROR   - init.lua:3

**Comment by Allaman** [comment]
Hello,
thanks for your Feedback. Can you please check again with the latest commits?

**Comment by Patil-Kranti** [comment]
Thanks for the update all 3 Errors got resolved but now i am getting this following error
 Error detected while processing /Users/krantipatil/.config/nvim/init.lua:
Failed to load `core.plugins.telescope`

...m/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'file_browser' extension doesn't exist or isn't installed: module 'telescope._extensions.file_browser' not found:
^Ino field package.preload['telescope._extensions.file_browser']
cache_loader: module telescope._extensions.file_browser not found
cache_loader_lib: module telescope._extensions.file_browser not found
^Ino file './telescope/_extensions/file_browser.lua'
^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/telescope/_extensions/file_browser.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/file_browser.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/file_browser/init.lua'
^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/telescope/_extensions/file_browser.lua'
^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/telescope/_extensions/file_browser/init.lua'
^Ino file './telescope/_extensions/file_browser.so'
^Ino file '/usr/local/lib/lua/5.1/telescope/_extensions/file_browser.so'
^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/telescope/_extensions/file_browser.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './telescope.so'
^Ino file '/usr/local/lib/lua/5.1/telescope.so'
^Ino file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/telescope.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /telescope.nvim/lua/telescope/_extensions/init.lua:10 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:17 _in_ **__index**
  - lua/core/plugins/telescope.lua:16 _in_ **file_browser_config**
  - lua/core/plugins/telescope.lua:107
  - lua/config/lazy.lua:20
  - lua/config/init.lua:32 _in_ **init**
  - lua/config/init.lua:37
  - init.lua:3

**Comment by Patil-Kranti** [comment]
Also getting these warnings and error messages whenever any file is opened.

   Warn  08:14:19 notify.warn ...llar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "lua-language-server" }` failed. The language server is either not installed, missing from PATH, or not executable.
   Warn  08:14:19 notify.warn ...llar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "lua-language-server" }` failed. The language server is either not installed, missing from PATH, or not executable.
   Error  08:14:19 notify.error Error running selene: ENOENT: no such file or directory

**Comment by Allaman** [comment]
Hello,
thanks for your valuable feedback! The first error should be fixed. 

Can you please run `:set filetype` and `:LspInfo` when this warning/error occurs?

**Comment by Patil-Kranti** [comment]
now getting the follwing error after the latest pull.
.../krantipatil/.config/nvim/lua/core/plugins/telescope.lua:83: attempt to index field 'telescope' (a nil value)

# stacktrace:
  - lua/core/plugins/telescope.lua:83 _in_ **config_function**
  - lua/core/plugins/telescope.lua:240 _in_ **config**
  - /telescope-file-browser.nvim/lua/telescope/_extensions/file_browser/finders.lua:12
  - /telescope-file-browser.nvim/lua/telescope/_extensions/file_browser.lua:55
  - /telescope.nvim/lua/telescope/_extensions/init.lua:8 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:17 _in_ **__index**
  - lua/core/plugins/telescope.lua:18 _in_ **file_browser_config**
  - lua/core/plugins/telescope.lua:274 _in_ **config**
  - lua/config/lazy.lua:20
  - lua/config/init.lua:32 _in_ **init**
  - lua/config/init.lua:37
  - init.lua:3
  -

**Comment by Patil-Kranti** [comment]
after running :set filetype 
got this   filetype=lua in Noice prompt. 

and :lspInfo gave following result
Language client log: /Users/krantipatil/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: lua
 
 Config: lua_ls
 	filetypes:         lua
 	root directory:    /Users/krantipatil/.config/nvim
 	cmd:               lua-language-server
 	cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tsserver, typst_lsp, yamlls, bashls, dockerls, jsonls, gopls, helm_ls, ltex, marksman, pyright, lua_ls, terraformls, texlab

**Comment by Allaman** [comment]
Getting closer. Thanks for your patience. Please take a look at the latest commit.

Thanks for your input. What file do you have opened? Neovim thinks that this is a Lua file, but you said that it happens on all files? Can you attach a "minimal not working" example file?

**Comment by Patil-Kranti** [comment]
thanks the latest commit fixed the telescope errors. 

I had telescope.lua opened while i got the previous error 

but it shows the same message for lsp for go or any otherfile type.

the following message i get when opening a simple go file 
...llar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "gopls" }` failed. The language server is either not installed, missing from PATH, or not executable.

# here is the code in the main.go file 


package main

import (
	"fmt"
)

func main() {

	fmt.Println("Hello World");
}

here is the :LspInfo result for the same go file:

 Language client log: /Users/krantipatil/.local/state/nvim/lsp.log
 Detected filetype:   go
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: go
 
 Config: gopls
 	filetypes:         go, gomod, gowork, gotmpl
 	root directory:    /Users/krantipatil/Projects/Go/trash
 	cmd:               gopls
 	cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: yamlls, bashls, dockerls, jsonls, gopls, helm_ls, ltex, marksman, pyright, lua_ls, terraformls, texlab, tsserver, typst_lsp

**Comment by Allaman** [comment]
Ahh, this is not "the same error on every file", so I was a little confused 😄 

> cmd: { "lua-language-server" } failed. 

this indicates that the LSP (lua-language-lsp in this case) is missing when having opened `telescope.lua`(a lua file)

> cmd: { "gopls" } failed.

this indicates that the LSP (gopls in this cae) is missing when having opened `main.go`(a Go file)

Have you seen the requirements in the README, especially [this](https://github.com/Allaman/nvim/?tab=readme-ov-file#all-other)? Mason is responsible for installing additional tools like gopls and lua-language-server.
If you don't need the default LSPs, you can overwrite it in your user config.

**Comment by Patil-Kranti** [comment]
yes I have mason installed all the requirements 
<img width="1615" alt="Screenshot 2024-05-05 at 8 25 54 PM" src="https://github.com/Allaman/nvim/assets/24855838/ade1896a-14a3-41af-a6f3-22f3888893f6">
<img width="1615" alt="Screenshot 2024-05-05 at 8 26 07 PM" src="https://github.com/Allaman/nvim/assets/24855838/af9f2f08-47a6-4ef6-9ae4-46d20fcbf4fa">

**Comment by Allaman** [comment]
hmm, can you check your PATH, both from your normal terminal and from a Neovim terminal? According to the Mason doc it should update the PATH itself. 
 
<img width="851" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/9ce2ab55-d971-4026-b9be-e23e5bad3084">

However, as I want the tools installed by Mason not only available in Neovim I added this to my .zshrc
`[ -d $HOME/.local/share/nvim/mason/bin ] && export PATH=$PATH:$HOME/.local/share/nvim/mason/bin`

**Comment by Patil-Kranti** [comment]
> [ -d $HOME/.local/share/nvim/mason/bin ] && export PATH=$PATH:$HOME/.local/share/nvim/mason/bin

running this and opening the file doesn't give any errors.

**Comment by Patil-Kranti** [comment]
adding mason to my $PATH worked. Thanks for the help and loving the config till now. again thanks for all the help

**Comment by Allaman** [comment]
Thank you for your feedback and patience!
