### ISSUE TITLE
keybindings for go testing?

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#82]
How to find out what keybindings are available for Go testing when editing go code.

**Comment by aphsa** [comment]
I tried to do a fresh install to fix this and I get the following error message after running nvim without any parameters.

```
Error detected while processing /home/aphsa/.config/nvim/init.lua:
Plugin telescope-file-browser.nvim is not installed
Press ENTER or type command to continue
```

**Comment by Allaman** [comment]
Hello, 

There are no default keybindings (yet) but you can use ex commands or define your own. 
<img width="776" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/f5605259-9434-4220-8bd0-44e8e4d6871f">


The plugin is called [gopher.nvim](https://github.com/olexsmir/gopher.nvim) and is disabled by default 
```lua
return {
  plugins = {
    gopher = {
      enable = true,
    },
}
```

**Comment by Allaman** [comment]
In general, you can enter `:map` to get a list of all (user defined) keybindings (or its variants `nmap`, `imap`, `vmap`, see `:help map`)

**Comment by aphsa** [comment]
That worked.
