### ISSUE TITLE
mapping function keys for go code

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#83]
Is there a way to map fn keys for running commands like make and its arguments specifically when using "go" files?

Something like this:

```lua
-- custom keys
function map(mode, shortcut, command)
  vim.api.nvim_set_keymap(mode, shortcut, command, { noremap = true, silent = true })
end

function nmap(shortcut, command)
  map('n', shortcut, command)
end


nmap("<F12>", "<cmd>!/usr/bin/make build")
```

If then where will this code go?

**Comment by Allaman** [comment]
Hello, 

`after/ftplugin/go.lua` is responsible for loading go specific stuff. Adding `vim.api.nvim_set_keymap("n", "<F12>", "<cmd>echo 'hello'<cr>", {})` works when opening a Go file.

PS: Your command is missing the ending `<cr>`.

PS2: I included overseer in the config (`lua/core/plugins/overseer.lua`) which is a plugin to run various tools including make goals.
<img width="964" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/8762add4-9ad5-4c23-b437-dabe2d5a485c">
