### ISSUE TITLE
LSP document diagnostics not showing anymore

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#85]
When I use the shortcut for LSP document diagnostics nothing pops up anymore. Anyone else?

**Comment by Allaman** [comment]
Hello @partounian ,

Thanks for opening this issue. The LSP mappings were a little messed up. I did some [rework](https://github.com/Allaman/nvim/commit/a8608d895321a0a4246de944f667f4eb0aed8fc2). 

However, if you are still facing issues, please run the commands behind the shortcuts directly.

* `Trouble symbols toggle` (if Trouble.nvim is enabled in your config)
* `Telescope lsp_document_symbols` (if Trouble.nvim is not enabled

If there are no diagnostics in the current document, Telescope will not pop up but show a warning when directly called via the command.
