### ISSUE TITLE
Can't select LSP 

### ISSUE THREAD

**Issue by shivam-909** [Allaman/nvim#9]
Hi,

Sorry in advance if this is a bit of a newbie question.

![image](https://user-images.githubusercontent.com/86538330/181351630-133e9b8a-25df-4380-adf1-3b8dd782d9a7.png)

I can't seem to use any method of switching windows that I know of to select an LSP here. How do you do it?

Thanks

**Comment by Allaman** [comment]
Hello,

honestly, I've never come over this selection. When does this window appear or how do you open it?

Usually (with my config), the correct LSPs automatically start when opening a buffer. This is handled by nvim-lspconfig. So for instance when I open a go file gopls and null-ls are automatically started.

**Comment by Allaman** [comment]
closed due to inactivity
